import type { ScheduleSlot } from '../../types/schedule'

interface ScheduleTimelineProps {
  slots: ScheduleSlot[]
  notes: string
}

export const ScheduleTimeline = ({ slots, notes }: ScheduleTimelineProps) => {
  return (
    <div className="bg-white/80 backdrop-blur-xl border border-slate-200/60 rounded-3xl p-8 shadow-xl relative overflow-hidden flex flex-col h-full">
      <div className="mb-6">
        <p className="text-xl font-bold text-slate-800 tracking-tight">Medication Timeline</p>
        <p className="text-sm font-semibold text-slate-400 mt-1 uppercase tracking-wider">Optimized spacing generated by scheduling engine.</p>
      </div>

      <div className="flex-1 space-y-5 relative before:absolute before:inset-y-0 before:left-[21px] before:w-1 before:bg-gradient-to-b before:from-teal-100 before:via-teal-200/50 before:to-transparent before:rounded-full pt-4">
        {slots.length === 0 ? (
          <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/50 p-6 text-sm text-slate-500 font-bold text-center">
            No schedule slots generated.
          </div>
        ) : (
          slots.map((slot, idx) => (
            <div key={`${slot.time}-${idx}`} className="relative z-10">
              <div className="flex items-start gap-4">
                <div className="flex-shrink-0 w-11 h-11 rounded-full border-4 border-white bg-teal-50 flex items-center justify-center text-xs font-black tracking-tighter text-teal-600 shadow-sm z-10 mt-1 transition-transform hover:scale-110">
                  {slot.time}
                </div>
                <div className="flex-1 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm hover:shadow-md hover:border-teal-200 transition-all group relative overflow-hidden">
                  <div className="absolute left-0 top-0 bottom-0 w-1 bg-teal-100 group-hover:bg-teal-400 transition-colors" />
                  <div className="flex flex-wrap gap-2 pl-2">
                    {slot.medications.map((med) => (
                      <span
                        key={`${slot.time}-${med}`}
                        className="rounded-full border border-teal-500/20 bg-teal-50/50 px-3 py-1.5 text-[11px] font-black uppercase tracking-widest text-teal-700 shadow-sm"
                      >
                        {med}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      <div className="mt-8 rounded-2xl border border-amber-200/50 bg-amber-50/50 p-5 text-sm text-slate-700 flex items-start gap-3 shadow-inner">
        <svg className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div>
          <span className="font-bold text-amber-700 block mb-1 uppercase tracking-wider text-xs">Clinical Note</span>
          <span className="text-slate-600 font-medium leading-relaxed">{notes}</span>
        </div>
      </div>
    </div>
  )
}
